//! Application discovery: user/all-users Start Menus, both Desktops, user
//! and public Documents, taskbar pins / Quick Launch, `shell:AppsFolder`
//! (Store/UWP apps), registry uninstall entries (64-bit and 32-bit views)
//! and common executable locations. Shortcuts are resolved through the
//! Windows Shell (`IShellLink` / `IPersistFile`); registered `App Paths`
//! and `Applications` entries cover apps with no shortcut; icons come from
//! `IShellItemImageFactory`; everything is cached in a persistent index.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::ffi::c_void;
use std::io::Cursor;
use std::path::{Path, PathBuf};
use std::process::Command;
use std::time::{Duration, SystemTime};

use windows::core::{w, Interface, GUID, PCWSTR, PWSTR};
use windows::Win32::Foundation::{HWND, SIZE};
use windows::Win32::Graphics::Gdi::{
    CreateCompatibleDC, DeleteDC, DeleteObject, GetDC, GetDIBits, GetObjectW, ReleaseDC,
    SelectObject, BITMAP, BITMAPINFO, BITMAPINFOHEADER, BI_RGB, DIB_RGB_COLORS, HBITMAP, HGDIOBJ,
};
use windows::Win32::Storage::EnhancedStorage::PKEY_AppUserModel_ID;
use windows::Win32::System::Com::StructuredStorage::{PropVariantClear, PROPVARIANT};
use windows::Win32::System::Com::{
    CoCreateInstance, CoInitializeEx, CoTaskMemFree, CoUninitialize, IPersistFile,
    CLSCTX_INPROC_SERVER, CLSCTX_LOCAL_SERVER, COINIT_APARTMENTTHREADED, STGM_READ,
};
use windows::Win32::System::Registry::{
    RegCloseKey, RegEnumKeyExW, RegOpenKeyExW, RegQueryValueExW, HKEY, HKEY_CLASSES_ROOT,
    HKEY_CURRENT_USER, HKEY_LOCAL_MACHINE, KEY_READ, KEY_WOW64_32KEY, KEY_WOW64_64KEY, REG_DWORD,
    REG_EXPAND_SZ, REG_SAM_FLAGS, REG_SZ, REG_VALUE_TYPE,
};
use windows::Win32::System::Variant::VT_LPWSTR;
use windows::Win32::UI::Shell::Common::ITEMIDLIST;
use windows::Win32::UI::Shell::PropertiesSystem::IPropertyStore;
use windows::Win32::UI::Shell::{
    ApplicationActivationManager, BHID_PropertyStore, BHID_SFObject, FOLDERID_CommonPrograms,
    FOLDERID_Desktop, FOLDERID_Documents, FOLDERID_LocalAppData, FOLDERID_Profile,
    FOLDERID_ProgramFiles, FOLDERID_ProgramFilesX86, FOLDERID_Programs, FOLDERID_PublicDesktop,
    FOLDERID_PublicDocuments, FOLDERID_RoamingAppData, IApplicationActivationManager, IEnumIDList,
    ILFree, IShellFolder, IShellItem, IShellItemImageFactory, IShellLinkW,
    SHCreateItemFromParsingName, SHCreateItemWithParent, SHGetIDListFromObject,
    SHGetKnownFolderPath, SHGetPathFromIDListW, ShellExecuteW, AO_NONE, SHCONTF_INCLUDEHIDDEN,
    SHCONTF_NONFOLDERS, SIGDN_NORMALDISPLAY, SIIGBF_ICONONLY,
};
use windows::Win32::UI::WindowsAndMessaging::SW_SHOWNORMAL;

const CACHE_TTL: Duration = Duration::from_secs(6 * 60 * 60);
/// Bump when the scan output format changes so stale caches rescan.
const APPS_CACHE_VERSION: u32 = 7;

/// CLSID_ShellLink (not generated by windows-rs).
const CLSID_SHELL_LINK: GUID = GUID::from_u128(0x00021401_0000_0000_c000_000000000046);

/// Directories that are never worth scanning (huge, system or cache dirs).
const SKIP_DIRS: &[&str] = &[
    "node_modules",
    ".git",
    ".svn",
    ".hg",
    ".cache",
    "Windows",
    "WindowsApps",
    "ModifiableWindowsApps",
    "Windows Kits",
    "Microsoft SDKs",
    "Common Files",
    "Windows Defender",
];

/// Registry display names that are bookkeeping, not launchable apps.
const REGISTRY_SKIP_FRAGMENTS: &[&str] = &[
    "redistributable",
    "visual c++",
    "runtime",
    "software development kit",
    "windows sdk",
    "universal crt",
];

/// Exe stems that are installers/helpers, never a product's main app.
const NOISE_STEMS: &[&str] = &[
    "unins000",
    "unins001",
    "uninstall",
    "uninst",
    "setup",
    "install",
    "installer",
    "vcredist",
    "vc_redist",
    "dxsetup",
    "redist",
    "dotnetfx",
    "repair",
    "postinstall",
    "prep",
    "wub",
];

#[derive(Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AppEntry {
    /// Friendly display name shown in the UI and matched first.
    pub name: String,
    /// Lowercased, punctuation-stripped name for exact matching.
    pub normalized_name: String,
    /// Stable unique id: the AUMID when present, else "target|arguments".
    pub app_id: String,
    /// Data-URL of the app's real icon (PNG), when it resolves.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub icon: Option<String>,
    /// Resolved launch target (exe path or web URL).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    /// Launch arguments (shortcut arguments), when present.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub args: Option<String>,
    /// Working directory from the shortcut, when set.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub working_directory: Option<String>,
    /// Original shortcut location (.lnk/.url path), when present.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub location: Option<String>,
    /// AppUserModelID for packaged apps, when available.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub aumid: Option<String>,
    /// Where the entry came from (startMenu/desktop/documents/profile/
    /// taskbar/appsFolder/registry/appPaths/applications/programs).
    pub source: String,
    /// Searchable aliases: exe names, folder names, publisher, description.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub keywords: Vec<String>,
}

/// Returns the cached scan when fresh, otherwise rescans and refreshes it.
pub fn scan(cache_path: &Path) -> Result<Vec<AppEntry>, String> {
    if cache_fresh(cache_path).unwrap_or(false) {
        if let Some(list) = load_cache(cache_path) {
            return Ok(list);
        }
    }
    scan_force(cache_path)
}

fn cache_fresh(path: &Path) -> Result<bool, String> {
    let meta = std::fs::metadata(path).map_err(|e| e.to_string())?;
    let age = SystemTime::now()
        .duration_since(meta.modified().map_err(|e| e.to_string())?)
        .unwrap_or_default();
    Ok(age < CACHE_TTL)
}

fn load_cache(path: &Path) -> Option<Vec<AppEntry>> {
    let text = std::fs::read_to_string(path).ok()?;
    let mut value: serde_json::Value = serde_json::from_str(&text).ok()?;
    if value.get("version").and_then(|v| v.as_u64()) != Some(APPS_CACHE_VERSION as u64) {
        return None;
    }
    // Take the apps value out instead of cloning the whole payload.
    value
        .get_mut("apps")
        .and_then(|apps| serde_json::from_value(std::mem::take(apps)).ok())
}

fn write_cache(path: &Path, apps: &[AppEntry]) {
    let value = serde_json::json!({ "version": APPS_CACHE_VERSION, "apps": apps });
    let text = serde_json::to_string(&value).unwrap_or_default();
    let _ = std::fs::create_dir_all(path.parent().unwrap_or(Path::new("")));
    // Atomic commit (temp file + replace) so a crash mid-write can never
    // corrupt the cache and force a full rescan.
    let temp = path.with_extension("json.tmp");
    if std::fs::write(&temp, text).is_ok() {
        let _ = crate::files::replace_file(&temp, path);
    }
}

/// Always rescans (used by the manual refresh button).
pub fn scan_force(cache_path: &Path) -> Result<Vec<AppEntry>, String> {
    let list = scan_raw()?;
    write_cache(cache_path, &list);
    Ok(list)
}

fn scan_raw() -> Result<Vec<AppEntry>, String> {
    let _com = ComGuard::init();
    let mut ctx = ScanCtx::new();
    ctx.scan_shortcut_roots();
    ctx.scan_apps_folder();
    ctx.scan_registry();
    ctx.scan_registered_apps();
    ctx.scan_program_files();
    ctx.apps.sort_by_cached_key(|app| app.name.to_lowercase());
    Ok(ctx.apps)
}

/* ---------------- shared scanning context ---------------- */

struct ScanCtx {
    icons: IconCache,
    /// Canonical keys: AUMID, or lowercase "target|args". First scan wins.
    seen: HashMap<String, ()>,
    apps: Vec<AppEntry>,
}

impl ScanCtx {
    fn new() -> Self {
        Self {
            icons: IconCache::new(icon_cache_dir()),
            seen: HashMap::new(),
            apps: Vec::new(),
        }
    }

    /// Adds an entry unless an identical app was already indexed.
    fn push(&mut self, entry: AppEntry) {
        if self.seen.insert(entry.app_id.clone(), ()).is_some() {
            return;
        }
        let mut entry = entry;
        entry.keywords = dedupe_keywords(entry.keywords);
        self.apps.push(entry);
    }
}

struct ComGuard {
    initialized: bool,
}

impl ComGuard {
    fn init() -> Self {
        Self {
            initialized: unsafe { CoInitializeEx(None, COINIT_APARTMENTTHREADED) }.is_ok(),
        }
    }
}

impl Drop for ComGuard {
    fn drop(&mut self) {
        // CoUninitialize must only balance a successful CoInitializeEx call.
        // In particular, RPC_E_CHANGED_MODE means this thread already belongs
        // to a different apartment and must be left untouched.
        if self.initialized {
            unsafe { CoUninitialize() }
        }
    }
}

/* ---------------- shortcut sources (Start Menu / Desktop / Documents / profile) ---------------- */

impl ScanCtx {
    fn scan_shortcut_roots(&mut self) {
        for (fid, source, depth, cap) in [
            (FOLDERID_Programs, "startMenu", 4u32, 2000usize),
            (FOLDERID_CommonPrograms, "startMenu", 4, 2000),
            (FOLDERID_Desktop, "desktop", 3, 800),
            (FOLDERID_PublicDesktop, "desktop", 3, 400),
            (FOLDERID_Documents, "documents", 3, 800),
            (FOLDERID_PublicDocuments, "documents", 3, 400),
            (FOLDERID_Profile, "profile", 1, 100),
        ] {
            if let Some(dir) = unsafe { known_folder(&fid) } {
                self.scan_shortcut_dir(&dir, source, depth, cap);
            }
        }
        // Taskbar pins and the classic Quick Launch area live under the
        // profile's AppData; both are small, curated shortcut stores.
        if let Some(profile) = unsafe { known_folder(&FOLDERID_Profile) } {
            let quick = profile
                .join("AppData")
                .join("Roaming")
                .join("Microsoft")
                .join("Internet Explorer")
                .join("Quick Launch");
            let taskbar = quick.join("User Pinned").join("TaskBar");
            self.scan_shortcut_dir(&quick, "taskbar", 1, 100);
            self.scan_shortcut_dir(&taskbar, "taskbar", 1, 100);
        }
    }

    fn scan_shortcut_dir(&mut self, root: &Path, source: &str, max_depth: u32, max_files: usize) {
        self.walk_shortcuts(root, source, max_depth, max_files, 0, &mut 0);
    }

    fn walk_shortcuts(
        &mut self,
        dir: &Path,
        source: &str,
        max_depth: u32,
        max_files: usize,
        depth: u32,
        count: &mut usize,
    ) {
        if depth > max_depth || *count >= max_files {
            return;
        }
        let Ok(entries) = std::fs::read_dir(dir) else {
            return;
        };
        for entry in entries.flatten() {
            if *count >= max_files {
                return;
            }
            let Ok(file_type) = entry.file_type() else {
                continue;
            };
            let Some(name) = entry.file_name().to_str().map(str::to_owned) else {
                continue;
            };
            if file_type.is_dir() {
                if SKIP_DIRS.contains(&name.as_str()) {
                    continue;
                }
                self.walk_shortcuts(
                    &entry.path(),
                    source,
                    max_depth,
                    max_files,
                    depth + 1,
                    count,
                );
            } else if file_type.is_file() {
                let lower = name.to_lowercase();
                if lower.ends_with(".lnk") {
                    *count += 1;
                    self.index_lnk(&entry.path(), source);
                } else if lower.ends_with(".url") {
                    *count += 1;
                    self.index_url(&entry.path(), source);
                }
            }
        }
    }

    fn index_lnk(&mut self, path: &Path, source: &str) {
        let Some(resolved) = resolve_lnk(path) else {
            return;
        };
        let aumid = read_lnk_aumid(path);
        let key = match &aumid {
            Some(a) => a.clone(),
            None => format!("{}|{}", resolved.target, resolved.args).to_lowercase(),
        };
        if self.seen.contains_key(&key) {
            return;
        }
        // Broken/dead shortcut: virtual targets (UWP AppsFolder links,
        // shell:/::{CLSID} targets) can't be stat-checked, everything else
        // must resolve to a file that exists on disk.
        let target_missing = resolved.target.is_empty()
            || (!looks_virtual(&resolved.target) && !Path::new(&resolved.target).exists());
        if aumid.is_none() && target_missing {
            return;
        }
        let name = path
            .file_stem()
            .map(|s| clean_name(&s.to_string_lossy()))
            .unwrap_or_default();
        if name.is_empty() {
            return;
        }
        let mut keywords = Vec::new();
        if let Some(stem) = Path::new(&resolved.target).file_stem() {
            keywords.push(stem.to_string_lossy().into_owned());
        }
        // Virtual shortcuts carry the app identity in their AUMID.
        if resolved.target.is_empty() {
            if let Some((package, app_id)) = aumid.as_deref().and_then(|a| a.split_once('!')) {
                keywords.push(package.to_string());
                keywords.push(app_id.to_string());
            }
        }
        if let Some(parent) = path.parent().and_then(|p| p.file_name()) {
            keywords.push(parent.to_string_lossy().into_owned());
        }
        if !resolved.description.is_empty() {
            keywords.push(resolved.description);
        }
        self.push(AppEntry {
            name: name.clone(),
            normalized_name: normalize(&name),
            app_id: key,
            // The shell resolves the shortcut's own (custom) icon.
            icon: self.icons.get(&path.to_string_lossy()),
            path: (!resolved.target.is_empty()).then_some(resolved.target),
            args: (!resolved.args.is_empty()).then_some(resolved.args),
            working_directory: (!resolved.working_directory.is_empty())
                .then_some(resolved.working_directory),
            location: Some(path.to_string_lossy().into_owned()),
            aumid,
            source: source.to_string(),
            keywords,
        });
    }

    fn index_url(&mut self, path: &Path, source: &str) {
        let Ok(text) = std::fs::read_to_string(path) else {
            return;
        };
        let mut url = None;
        let mut icon_file = None;
        for line in text.lines() {
            let line = line.trim();
            if let Some(value) = line.strip_prefix("URL=") {
                url = Some(value);
            } else if let Some(value) = line.strip_prefix("IconFile=") {
                icon_file = Some(value);
            }
        }
        // Accept any registered scheme (http(s), steam://, game launcher
        // protocols...); the shell resolves the handler on launch.
        let Some(url) = url else {
            return;
        };
        if !url.contains("://") {
            return;
        }
        let key = format!("url|{}", url.to_lowercase());
        if self.seen.contains_key(&key) {
            return;
        }
        let name = path
            .file_stem()
            .map(|s| clean_name(&s.to_string_lossy()))
            .unwrap_or_default();
        if name.is_empty() {
            return;
        }
        // Prefer the .url's explicit IconFile (real game/app icons), falling
        // back to the shell icon for the .url file itself.
        let icon_file = icon_file.map(|f| expand_env(f).trim().to_string());
        let icon = match icon_file {
            Some(file) if !file.is_empty() && Path::new(&file).exists() => self.icons.get(&file),
            _ => self.icons.get(&path.to_string_lossy()),
        };
        let host = url.split("://").next().unwrap_or("").to_lowercase();
        let mut keywords = vec![host];
        if let Some(rest) = url.split("://").nth(1) {
            if let Some(domain) = rest.split('/').next() {
                if !domain.is_empty() {
                    keywords.push(domain.to_lowercase());
                }
            }
        }
        self.push(AppEntry {
            name: name.clone(),
            normalized_name: normalize(&name),
            app_id: key,
            icon,
            path: Some(url.to_string()),
            args: None,
            working_directory: None,
            location: Some(path.to_string_lossy().into_owned()),
            aumid: None,
            source: source.to_string(),
            keywords,
        });
    }
}

/// Resolved IShellLink state for a single .lnk file.
struct ResolvedLnk {
    target: String,
    args: String,
    working_directory: String,
    description: String,
}

/// Resolves a shortcut through the Windows Shell COM APIs
/// (IShellLink + IPersistFile), returning its real target, arguments,
/// working directory and description. Returns None for unreadable links.
fn resolve_lnk(path: &Path) -> Option<ResolvedLnk> {
    unsafe {
        let link: IShellLinkW =
            CoCreateInstance(&CLSID_SHELL_LINK, None, CLSCTX_INPROC_SERVER).ok()?;
        let persist: IPersistFile = link.cast().ok()?;
        let wide_path = wide(&path.to_string_lossy());
        persist.Load(PCWSTR(wide_path.as_ptr()), STGM_READ).ok()?;

        // Resolve the target through the shortcut's IDList; this also
        // expands environment variables and follows special folders. Virtual
        // shortcuts (UWP apps) resolve to no filesystem path - the caller
        // detects those via the AUMID and keeps the link itself.
        let target = {
            let pidl = link.GetIDList().ok()?;
            let mut buffer = [0u16; 260];
            let path = if SHGetPathFromIDListW(pidl, &mut buffer).as_bool() {
                wide_trim(&buffer)
            } else {
                String::new()
            };
            CoTaskMemFree(Some(pidl as *const c_void));
            path
        };
        let args = read_buf16(|buf| link.GetArguments(buf));
        let working_directory = read_buf16(|buf| link.GetWorkingDirectory(buf));
        let description = read_buf16(|buf| link.GetDescription(buf));
        Some(ResolvedLnk {
            target,
            args,
            working_directory,
            description,
        })
    }
}

/// Reads System.AppUserModel.ID off a .lnk file so Store/UWP shortcuts are
/// keyed (and launched) by their AUMID.
fn read_lnk_aumid(path: &Path) -> Option<String> {
    unsafe {
        let wide_path = wide(&path.to_string_lossy());
        let store: IPropertyStore =
            SHCreateItemFromParsingName(PCWSTR(wide_path.as_ptr()), None).ok()?;
        let mut value = store.GetValue(&PKEY_AppUserModel_ID).ok()?;
        let result = prop_lpwstr(&value);
        let _ = PropVariantClear(&mut value);
        result
    }
}

/* ---------------- shell:AppsFolder (packaged / Store apps) ---------------- */

impl ScanCtx {
    fn scan_apps_folder(&mut self) {
        unsafe {
            let item: IShellItem =
                match SHCreateItemFromParsingName(PCWSTR(w!("shell:AppsFolder").as_ptr()), None) {
                    Ok(item) => item,
                    Err(_) => return,
                };
            let folder: IShellFolder = match item.BindToHandler(None, &BHID_SFObject) {
                Ok(folder) => folder,
                Err(_) => return,
            };
            let mut enumerator: Option<IEnumIDList> = None;
            let hr = folder.EnumObjects(
                HWND(std::ptr::null_mut()),
                SHCONTF_NONFOLDERS.0 as u32 | SHCONTF_INCLUDEHIDDEN.0 as u32,
                &mut enumerator,
            );
            if !hr.is_ok() {
                return;
            }
            let Some(enumerator) = enumerator else {
                return;
            };
            // Enumeration yields *child* PIDLs; an absolute parent PIDL is
            // needed to build shell items for them.
            let Ok(parent_pidl) = SHGetIDListFromObject(&folder) else {
                return;
            };
            loop {
                let mut pidls: [*mut ITEMIDLIST; 1] = [std::ptr::null_mut()];
                let hr = enumerator.Next(&mut pidls, None);
                let pidl = pidls[0];
                if pidl.is_null() || !hr.is_ok() {
                    break;
                }
                self.index_apps_folder_item(&folder, parent_pidl, pidl);
                ILFree(Some(pidl));
            }
            ILFree(Some(parent_pidl));
        }
    }

    fn index_apps_folder_item(
        &mut self,
        folder: &IShellFolder,
        parent_pidl: *const ITEMIDLIST,
        pidl: *mut ITEMIDLIST,
    ) {
        unsafe {
            // Build the real shell item for the child so display name and
            // property store resolve correctly.
            let Ok(item) =
                SHCreateItemWithParent(Some(parent_pidl), folder, pidl).map(|i: IShellItem| i)
            else {
                return;
            };
            let Ok(name_ptr) = item.GetDisplayName(SIGDN_NORMALDISPLAY) else {
                return;
            };
            let name = name_ptr.to_string().unwrap_or_default();
            CoTaskMemFree(Some(name_ptr.as_ptr() as *const c_void));
            let name = name.trim().to_string();
            if name.is_empty() {
                return;
            }
            let Ok(store) = item.BindToHandler::<_, IPropertyStore>(None, &BHID_PropertyStore)
            else {
                return;
            };
            let Ok(mut value) = store.GetValue(&PKEY_AppUserModel_ID) else {
                return;
            };
            let aumid = prop_lpwstr(&value);
            let _ = PropVariantClear(&mut value);
            let Some(aumid) = aumid else {
                return;
            };
            if aumid.is_empty() {
                return;
            }
            let mut keywords = Vec::new();
            if let Some((package, app_id)) = aumid.split_once('!') {
                keywords.push(package.to_string());
                keywords.push(app_id.to_string());
            }
            // Desktop apps surface in AppsFolder with a {GUID}\relative
            // AppID. Resolve those to real paths so they dedupe against
            // shortcuts/registry entries and launch directly.
            if aumid.starts_with('{') {
                let Some(path) = resolve_guid_appid(&aumid) else {
                    return;
                };
                let key = path.to_lowercase();
                if self.seen.contains_key(&key) {
                    return;
                }
                let mut exe_keywords = Vec::new();
                if let Some(stem) = Path::new(&path).file_stem() {
                    exe_keywords.push(stem.to_string_lossy().into_owned());
                }
                self.push(AppEntry {
                    name: name.clone(),
                    normalized_name: normalize(&name),
                    app_id: key,
                    icon: self.icons.get(&path),
                    path: Some(path),
                    args: None,
                    working_directory: None,
                    location: None,
                    aumid: None,
                    source: "appsFolder".to_string(),
                    keywords: exe_keywords,
                });
                return;
            }
            if self.seen.contains_key(&aumid) {
                return;
            }
            self.push(AppEntry {
                name: name.clone(),
                normalized_name: normalize(&name),
                app_id: aumid.clone(),
                icon: self.icons.get_with(&format!("apps-folder-v2|{aumid}"), || {
                    extract_apps_folder_icon(&item, folder, pidl)
                }),
                path: None,
                args: None,
                working_directory: None,
                location: None,
                aumid: Some(aumid),
                source: "appsFolder".to_string(),
                keywords,
            });
        }
    }
}

/// Resolves `{KNOWN_FOLDER_GUID}\relative\path` AppIDs (what Get-StartApps
/// reports for desktop apps) to a real file path.
fn resolve_guid_appid(app_id: &str) -> Option<String> {
    let (guid, relative) = app_id.split_once('\\')?;
    let mut candidates: Vec<PathBuf> = Vec::new();
    if guid.eq_ignore_ascii_case("{1AC14E77-02E7-4E5D-B744-2EB1AE5198B7}") {
        if let Some(root) = std::env::var_os("SystemRoot") {
            candidates.push(PathBuf::from(root).join("System32").join(relative));
        }
    } else if guid.eq_ignore_ascii_case("{6D809377-6AF0-444B-8957-A3773F02200E}") {
        if let Some(root) = std::env::var_os("ProgramFiles") {
            candidates.push(PathBuf::from(root).join(relative));
        }
    } else {
        // Unknown folder GUID: probe the common install roots.
        for root in [
            std::env::var_os("ProgramFiles").map(PathBuf::from),
            std::env::var_os("ProgramFiles(x86)").map(PathBuf::from),
            std::env::var_os("LOCALAPPDATA").map(|p| PathBuf::from(p).join("Programs")),
            std::env::var_os("SystemRoot").map(|p| PathBuf::from(p).join("System32")),
        ]
        .into_iter()
        .flatten()
        {
            candidates.push(root.join(relative));
        }
    }
    candidates
        .into_iter()
        .find(|candidate| candidate.exists())
        .map(|candidate| candidate.to_string_lossy().into_owned())
}

/* ---------------- registry uninstall entries ---------------- */

const UNINSTALL_SUBKEY: &str = r"SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall";
const APP_PATHS_SUBKEY: &str = r"SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths";

impl ScanCtx {
    fn scan_registry(&mut self) {
        for (hive, view) in [
            (HKEY_LOCAL_MACHINE, KEY_WOW64_64KEY),
            (HKEY_LOCAL_MACHINE, KEY_WOW64_32KEY),
            (HKEY_CURRENT_USER, KEY_WOW64_64KEY),
        ] {
            self.scan_uninstall_hive(hive, view);
        }
    }

    fn scan_uninstall_hive(&mut self, hive: HKEY, view: REG_SAM_FLAGS) {
        unsafe {
            let Ok(root) = open_key(hive, UNINSTALL_SUBKEY, view) else {
                return;
            };
            let mut index = 0u32;
            loop {
                let mut name_buf = [0u16; 512];
                let mut len = 512u32;
                let err = RegEnumKeyExW(
                    root,
                    index,
                    Some(PWSTR(name_buf.as_mut_ptr())),
                    &mut len,
                    None,
                    None,
                    None,
                    None,
                );
                if err.0 != 0 {
                    break;
                }
                index += 1;
                let key_name = String::from_utf16_lossy(&name_buf[..len as usize]);
                let Ok(subkey) = open_key(root, &key_name, KEY_READ) else {
                    continue;
                };
                self.index_registry_entry(subkey);
                let _ = RegCloseKey(subkey);
            }
            let _ = RegCloseKey(root);
        }
    }

    fn index_registry_entry(&mut self, hk: HKEY) {
        unsafe {
            let Some(name) = reg_string(hk, "DisplayName") else {
                return;
            };
            let name = name.trim().to_string();
            if name.is_empty() {
                return;
            }
            // Windows update / component bookkeeping, not launchable apps.
            if reg_dword(hk, "SystemComponent") == Some(1) {
                return;
            }
            if let Some(release_type) = reg_string(hk, "ReleaseType") {
                let lower = release_type.to_lowercase();
                if matches!(
                    lower.as_str(),
                    "security update"
                        | "update"
                        | "hotfix"
                        | "update rollup"
                        | "feature pack"
                        | "critical update"
                        | "service pack"
                ) {
                    return;
                }
            }
            if reg_string(hk, "ParentKeyName").is_some() {
                return;
            }
            let lower = name.to_lowercase();
            if lower.starts_with("kb")
                && lower.len() > 8
                && lower[2..].chars().all(|c| c.is_ascii_digit())
            {
                return;
            }
            if REGISTRY_SKIP_FRAGMENTS
                .iter()
                .any(|frag| lower.contains(frag))
            {
                return;
            }
            let display_icon = reg_string(hk, "DisplayIcon").unwrap_or_default();
            let install_location = reg_string(hk, "InstallLocation").unwrap_or_default();
            let display_icon = expand_env(&display_icon);
            let install_location = expand_env(&install_location);
            let exe = parse_icon_path(&display_icon).or_else(|| {
                if install_location.is_empty() {
                    None
                } else {
                    find_exe_in(&PathBuf::from(&install_location), &name)
                }
            });
            let Some(exe) = exe else {
                return;
            };
            if !exe
                .extension()
                .and_then(|e| e.to_str())
                .map(|e| e.eq_ignore_ascii_case("exe"))
                .unwrap_or(false)
            {
                return;
            }
            // Stale installs reference exes that no longer exist - drop them.
            if !exe.exists() {
                return;
            }
            let exe_str = exe.to_string_lossy().into_owned();
            let key = format!("{}|", exe_str.to_lowercase());
            if self.seen.contains_key(&key) {
                return;
            }
            let mut keywords = Vec::new();
            if let Some(stem) = exe.file_stem() {
                keywords.push(stem.to_string_lossy().into_owned());
            }
            if let Some(publisher) = reg_string(hk, "Publisher") {
                keywords.push(publisher);
            }
            if let Some(version) = reg_string(hk, "DisplayVersion") {
                keywords.push(version);
            }
            self.push(AppEntry {
                name: name.clone(),
                normalized_name: normalize(&name),
                app_id: key,
                icon: self.icons.get(&exe_str),
                path: Some(exe_str),
                args: None,
                working_directory: None,
                location: None,
                aumid: None,
                source: "registry".to_string(),
                keywords,
            });
        }
    }
}

/* ---------------- registered apps without shortcuts ---------------- */

impl ScanCtx {
    fn scan_registered_apps(&mut self) {
        for (hive, view) in [
            (HKEY_LOCAL_MACHINE, KEY_WOW64_64KEY),
            (HKEY_LOCAL_MACHINE, KEY_WOW64_32KEY),
            (HKEY_CURRENT_USER, KEY_WOW64_64KEY),
            (HKEY_CURRENT_USER, KEY_WOW64_32KEY),
        ] {
            self.scan_app_paths_hive(hive, view);
        }
        for view in [KEY_WOW64_64KEY, KEY_WOW64_32KEY] {
            self.scan_applications_registry(view);
        }
    }

    fn scan_app_paths_hive(&mut self, hive: HKEY, view: REG_SAM_FLAGS) {
        unsafe {
            let Ok(root) = open_key(hive, APP_PATHS_SUBKEY, view) else {
                return;
            };
            let mut index = 0u32;
            loop {
                let mut name_buf = [0u16; 512];
                let mut len = name_buf.len() as u32;
                let error = RegEnumKeyExW(
                    root,
                    index,
                    Some(PWSTR(name_buf.as_mut_ptr())),
                    &mut len,
                    None,
                    None,
                    None,
                    None,
                );
                if error.0 != 0 {
                    break;
                }
                index += 1;
                let key_name = String::from_utf16_lossy(&name_buf[..len as usize]);
                if !key_name.to_lowercase().ends_with(".exe") {
                    continue;
                }
                let Ok(key) = open_key(root, &key_name, KEY_READ) else {
                    continue;
                };
                let executable = reg_string(key, "")
                    .map(|value| expand_env(&value))
                    .and_then(|value| parse_registered_executable(&value));
                let _ = RegCloseKey(key);
                if let Some(executable) = executable {
                    self.index_registered_exe(executable, None, "appPaths", vec![key_name]);
                }
            }
            let _ = RegCloseKey(root);
        }
    }

    fn scan_applications_registry(&mut self, view: REG_SAM_FLAGS) {
        unsafe {
            let Ok(root) = open_key(HKEY_CLASSES_ROOT, "Applications", view) else {
                return;
            };
            let mut index = 0u32;
            loop {
                let mut name_buf = [0u16; 512];
                let mut len = name_buf.len() as u32;
                let error = RegEnumKeyExW(
                    root,
                    index,
                    Some(PWSTR(name_buf.as_mut_ptr())),
                    &mut len,
                    None,
                    None,
                    None,
                    None,
                );
                if error.0 != 0 {
                    break;
                }
                index += 1;
                let key_name = String::from_utf16_lossy(&name_buf[..len as usize]);
                if !key_name.to_lowercase().ends_with(".exe") {
                    continue;
                }
                let Ok(key) = open_key(root, &key_name, KEY_READ) else {
                    continue;
                };
                if reg_value_exists(key, "NoStartPage") || reg_value_exists(key, "IsHostApp") {
                    let _ = RegCloseKey(key);
                    continue;
                }
                let friendly_name = reg_string(key, "FriendlyAppName")
                    .filter(|name| !name.starts_with('@') && !name.trim().is_empty());
                let executable = open_key(key, r"shell\open\command", KEY_READ)
                    .ok()
                    .and_then(|command_key| {
                        let value = reg_string(command_key, "")
                            .map(|value| expand_env(&value))
                            .and_then(|value| parse_registered_executable(&value));
                        let _ = RegCloseKey(command_key);
                        value
                    });
                let _ = RegCloseKey(key);
                if let Some(executable) = executable {
                    self.index_registered_exe(
                        executable,
                        friendly_name,
                        "applications",
                        vec![key_name],
                    );
                }
            }
            let _ = RegCloseKey(root);
        }
    }

    fn index_registered_exe(
        &mut self,
        executable: PathBuf,
        friendly_name: Option<String>,
        source: &str,
        mut keywords: Vec<String>,
    ) {
        if !executable.is_file()
            || !executable
                .extension()
                .is_some_and(|extension| extension.eq_ignore_ascii_case("exe"))
        {
            return;
        }
        let Some(stem) = executable
            .file_stem()
            .map(|stem| stem.to_string_lossy().into_owned())
        else {
            return;
        };
        let lower_stem = stem.to_lowercase();
        if NOISE_STEMS
            .iter()
            .any(|noise| lower_stem.starts_with(noise))
        {
            return;
        }
        let path = executable.to_string_lossy().into_owned();
        let key = format!("{}|", path.to_lowercase());
        if self.seen.contains_key(&key) {
            return;
        }
        let name = friendly_name.unwrap_or_else(|| clean_name(&stem));
        if name.trim().is_empty() {
            return;
        }
        keywords.push(stem);
        if let Some(parent) = executable.parent().and_then(Path::file_name) {
            keywords.push(parent.to_string_lossy().into_owned());
        }
        self.push(AppEntry {
            name: name.clone(),
            normalized_name: normalize(&name),
            app_id: key,
            icon: self.icons.get(&path),
            path: Some(path),
            args: None,
            working_directory: None,
            location: None,
            aumid: None,
            source: source.to_string(),
            keywords,
        });
    }
}

/* ---------------- common executable locations ---------------- */

impl ScanCtx {
    fn scan_program_files(&mut self) {
        let mut roots = Vec::new();
        for fid in [FOLDERID_ProgramFiles, FOLDERID_ProgramFilesX86] {
            if let Some(dir) = unsafe { known_folder(&fid) } {
                roots.push(dir);
            }
        }
        if let Some(local) = unsafe { known_folder(&FOLDERID_LocalAppData) } {
            roots.push(local.join("Programs"));
        }
        for root in roots {
            let Ok(entries) = std::fs::read_dir(&root) else {
                continue;
            };
            let mut products = 0usize;
            for entry in entries.flatten() {
                if products >= 400 {
                    break;
                }
                let Ok(file_type) = entry.file_type() else {
                    continue;
                };
                if !file_type.is_dir() {
                    continue;
                }
                let product = entry.file_name().to_string_lossy().into_owned();
                if product.starts_with('.') || SKIP_DIRS.contains(&product.as_str()) {
                    continue;
                }
                products += 1;
                if let Some(exe) = pick_main_exe(&entry.path(), &product) {
                    self.index_exe(exe, &product);
                }
            }
        }
    }

    fn index_exe(&mut self, exe: PathBuf, product: &str) {
        let exe_str = exe.to_string_lossy().into_owned();
        let key = format!("{}|", exe_str.to_lowercase());
        if self.seen.contains_key(&key) {
            return;
        }
        let Some(stem) = exe.file_stem().map(|s| s.to_string_lossy().into_owned()) else {
            return;
        };
        if stem.is_empty() {
            return;
        }
        let name = clean_name(&stem);
        let mut keywords = vec![product.to_string(), stem];
        if let Some(parent) = exe.parent().and_then(|p| p.file_name()) {
            keywords.push(parent.to_string_lossy().into_owned());
        }
        self.push(AppEntry {
            name: name.clone(),
            normalized_name: normalize(&name),
            app_id: key,
            icon: self.icons.get(&exe_str),
            path: Some(exe_str),
            args: None,
            working_directory: None,
            location: None,
            aumid: None,
            source: "programs".to_string(),
            keywords,
        });
    }
}

/// Picks the "main" executable of an installed-product folder: the exe whose
/// stem matches the product folder name, else the largest exe near the root.
fn pick_main_exe(product_dir: &Path, product: &str) -> Option<PathBuf> {
    let product_lower = product.to_lowercase();
    let mut exact: Option<(u32, i64, PathBuf)> = None;
    let mut shallow: Option<(i64, PathBuf)> = None;
    let mut deep: Option<(i64, PathBuf)> = None;
    walk_exes(product_dir, 0, &mut 0, &mut |depth, path| {
        let stem = path
            .file_stem()
            .map(|s| s.to_string_lossy().to_lowercase())
            .unwrap_or_default();
        let size = path.metadata().map(|m| m.len() as i64).unwrap_or(0);
        if stem != product_lower && NOISE_STEMS.iter().any(|n| stem.starts_with(n)) {
            return;
        }
        if stem == product_lower {
            let better = exact
                .as_ref()
                .is_none_or(|(d, s, _)| depth < *d || (depth == *d && size > *s));
            if better {
                exact = Some((depth, size, path.to_path_buf()));
            }
        } else if depth <= 2 {
            if shallow.as_ref().is_none_or(|(s, _)| size > *s) {
                shallow = Some((size, path.to_path_buf()));
            }
        } else if deep.as_ref().is_none_or(|(s, _)| size > *s) {
            deep = Some((size, path.to_path_buf()));
        }
    });
    if let Some((_, _, path)) = exact {
        return Some(path);
    }
    if let Some((size, path)) = shallow {
        if size >= 64 * 1024 {
            return Some(path);
        }
    }
    if let Some((size, path)) = deep {
        if size >= 256 * 1024 {
            return Some(path);
        }
    }
    None
}

fn walk_exes(dir: &Path, depth: u32, count: &mut usize, on_file: &mut impl FnMut(u32, &Path)) {
    if depth > 3 || *count > 600 {
        return;
    }
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let Ok(file_type) = entry.file_type() else {
            continue;
        };
        if file_type.is_dir() {
            if depth >= 3 {
                continue;
            }
            let name = entry.file_name().to_string_lossy().into_owned();
            if matches!(name.as_str(), "node_modules" | ".git" | ".svn" | ".hg") {
                continue;
            }
            walk_exes(&entry.path(), depth + 1, count, on_file);
        } else if file_type.is_file() {
            let path = entry.path();
            let Some(ext) = path.extension() else {
                continue;
            };
            if ext.to_string_lossy().eq_ignore_ascii_case("exe") {
                *count += 1;
                on_file(depth, &path);
            }
        }
    }
}

/* ---------------- icons ---------------- */

struct IconCache {
    dir: PathBuf,
}

impl IconCache {
    fn new(dir: PathBuf) -> Self {
        Self { dir }
    }

    /// Returns a PNG data-URL for a filesystem source (a path, .lnk or
    /// .url). Extracted PNGs are cached on disk keyed by source hash so
    /// rescans are fast.
    fn get(&self, source: &str) -> Option<String> {
        self.load_or(&hash(source), || unsafe { extract_file_icon(source) })
    }

    /// Same as `get`, but extraction is provided by the caller (used for
    /// virtual shell items that need their enumerated child PIDL).
    fn get_with(&self, key: &str, extract: impl FnOnce() -> Option<Vec<u8>>) -> Option<String> {
        self.load_or(&hash(key), extract)
    }

    fn load_or(&self, key: &str, extract: impl FnOnce() -> Option<Vec<u8>>) -> Option<String> {
        let png_path = self.dir.join(format!("{key}.png"));
        if let Ok(bytes) = std::fs::read(&png_path) {
            return Some(png_data_url(&bytes));
        }
        let png = extract()?;
        let _ = std::fs::create_dir_all(&self.dir);
        let _ = std::fs::write(&png_path, &png);
        Some(png_data_url(&png))
    }
}

/// Extracts an icon for a filesystem path (exe, ico, .lnk or .url) via
/// SHGetFileInfoW, which lets the shell resolve shortcut icons.
unsafe fn extract_file_icon(path: &str) -> Option<Vec<u8>> {
    use windows::Win32::Storage::FileSystem::FILE_FLAGS_AND_ATTRIBUTES;
    use windows::Win32::UI::Shell::{
        SHGetFileInfoW, SHFILEINFOW, SHGFI_FLAGS, SHGFI_ICON, SHGFI_LARGEICON,
    };
    use windows::Win32::UI::WindowsAndMessaging::DestroyIcon;

    let wide_path = wide(path);
    let mut info = std::mem::zeroed::<SHFILEINFOW>();
    let result = SHGetFileInfoW(
        PCWSTR(wide_path.as_ptr()),
        FILE_FLAGS_AND_ATTRIBUTES(0),
        Some(&mut info),
        std::mem::size_of::<SHFILEINFOW>() as u32,
        SHGFI_FLAGS(SHGFI_ICON.0 | SHGFI_LARGEICON.0),
    );
    if result == 0 || info.hIcon.0.is_null() {
        return None;
    }
    let png = hicon_to_png(info.hIcon);
    let _ = DestroyIcon(info.hIcon);
    png
}

/// Extracts an icon for a virtual AppsFolder item through the Shell image
/// factory. Modern AppX/MSIX apps expose their package logo this way rather
/// than as an icon resource filename. Older shell extensions fall back to
/// IExtractIconW below.
unsafe fn extract_apps_folder_icon(
    item: &IShellItem,
    folder: &IShellFolder,
    pidl: *mut ITEMIDLIST,
) -> Option<Vec<u8>> {
    if let Ok(factory) = item.cast::<IShellItemImageFactory>() {
        if let Ok(bitmap) = factory.GetImage(SIZE { cx: 64, cy: 64 }, SIIGBF_ICONONLY) {
            if let Some(png) = bitmap_to_png(bitmap) {
                return Some(png);
            }
        }
    }

    extract_legacy_apps_folder_icon(folder, pidl)
}

unsafe fn extract_legacy_apps_folder_icon(
    folder: &IShellFolder,
    pidl: *mut ITEMIDLIST,
) -> Option<Vec<u8>> {
    use windows::Win32::UI::Shell::{
        ExtractIconExW, IExtractIconW, GIL_FORSHELL, GIL_NOTFILENAME, GIL_OPENICON,
    };
    use windows::Win32::UI::WindowsAndMessaging::{DestroyIcon, HICON};

    let icon: IExtractIconW = folder
        .GetUIObjectOf(
            HWND(std::ptr::null_mut()),
            &[pidl as *const ITEMIDLIST],
            None,
        )
        .ok()?;
    let mut path_buf = [0u16; 260];
    let mut index = 0i32;
    let mut flags = 0u32;
    icon.GetIconLocation(
        GIL_OPENICON | GIL_FORSHELL,
        &mut path_buf,
        &mut index,
        &mut flags,
    )
    .ok()?;
    let path = wide_trim(&path_buf);
    let mut hicon = HICON(std::ptr::null_mut());
    // GIL_NOTFILENAME means pszIconFile is a resource spec, not a file.
    if flags & GIL_NOTFILENAME == 0 && !path.is_empty() {
        let wide_path = wide(&path);
        let count = ExtractIconExW(PCWSTR(wide_path.as_ptr()), index, Some(&mut hicon), None, 1);
        if count == 0 {
            hicon.0 = std::ptr::null_mut();
        }
    }
    if hicon.0.is_null() {
        let wide_path = wide(&path);
        icon.Extract(
            PCWSTR(wide_path.as_ptr()),
            index as u32,
            Some(&mut hicon),
            None,
            0,
        )
        .ok()?;
    }
    if hicon.0.is_null() {
        return None;
    }
    let png = hicon_to_png(hicon);
    let _ = DestroyIcon(hicon);
    png
}

/// Converts an HICON to PNG bytes: GetIconInfo gives the color bitmap,
/// which bitmap_to_png renders (BGRA -> RGBA with alpha handling).
unsafe fn hicon_to_png(icon: windows::Win32::UI::WindowsAndMessaging::HICON) -> Option<Vec<u8>> {
    use windows::Win32::Graphics::Gdi::HGDIOBJ;
    use windows::Win32::UI::WindowsAndMessaging::{GetIconInfo, ICONINFO};

    let mut info = std::mem::zeroed::<ICONINFO>();
    if GetIconInfo(icon, &mut info).is_err() {
        return None;
    }
    let color = info.hbmColor;
    let mask = info.hbmMask;
    let png = if !color.0.is_null() {
        bitmap_to_png(color)
    } else {
        // Monochrome icons carry no color bitmap; skip rather than render
        // a black square.
        let _ = DeleteObject(HGDIOBJ(mask.0));
        None
    };
    if !color.0.is_null() && !mask.0.is_null() {
        let _ = DeleteObject(HGDIOBJ(mask.0));
    }
    png
}

/// Converts an HBITMAP to PNG bytes (BGRA -> RGBA via GetDIBits, with
/// premultiplied-alpha and no-alpha handling). Always consumes the bitmap.
unsafe fn bitmap_to_png(bitmap: HBITMAP) -> Option<Vec<u8>> {
    let bitmap_handle = HGDIOBJ(bitmap.0);
    let mut bmp: BITMAP = std::mem::zeroed();
    let copied = GetObjectW(
        bitmap_handle,
        std::mem::size_of::<BITMAP>() as i32,
        Some(&mut bmp as *mut _ as *mut c_void),
    );
    if copied == 0 {
        let _ = DeleteObject(bitmap_handle);
        return None;
    }
    let width = bmp.bmWidth;
    let height = bmp.bmHeight;
    if width <= 0 || height <= 0 || width > 512 || height > 512 {
        let _ = DeleteObject(bitmap_handle);
        return None;
    }
    let screen = GetDC(None);
    let memory = CreateCompatibleDC(Some(screen));
    let old = SelectObject(memory, bitmap_handle);
    let mut info: BITMAPINFO = std::mem::zeroed();
    info.bmiHeader.biSize = std::mem::size_of::<BITMAPINFOHEADER>() as u32;
    info.bmiHeader.biWidth = width;
    info.bmiHeader.biHeight = -height; // top-down rows
    info.bmiHeader.biPlanes = 1;
    info.bmiHeader.biBitCount = 32;
    info.bmiHeader.biCompression = BI_RGB.0;
    let mut pixels = vec![0u8; width as usize * height as usize * 4];
    let lines = GetDIBits(
        memory,
        bitmap,
        0,
        height as u32,
        Some(pixels.as_mut_ptr() as *mut c_void),
        &mut info,
        DIB_RGB_COLORS,
    );
    let _ = SelectObject(memory, old);
    let _ = DeleteDC(memory);
    if !screen.is_invalid() {
        let _ = ReleaseDC(None, screen);
    }
    let _ = DeleteObject(bitmap_handle);
    if lines <= 0 {
        return None;
    }
    // GetDIBits yields BGRA; shell bitmaps arrive with premultiplied alpha.
    let has_alpha = pixels.chunks_exact(4).any(|p| p[3] != 0);
    if !has_alpha {
        // No alpha channel: the 32-bit conversion filled 0s - force opaque.
        for px in pixels.chunks_exact_mut(4) {
            px[3] = 255;
        }
    } else {
        for px in pixels.chunks_exact_mut(4) {
            let (b, g, r, a) = (px[0] as u32, px[1] as u32, px[2] as u32, px[3] as u32);
            let scale = |c: u32| ((c * 255) / a.max(1)).min(255) as u8;
            px[0] = scale(r);
            px[1] = scale(g);
            px[2] = scale(b);
        }
    }
    let image = image::RgbaImage::from_raw(width as u32, height as u32, pixels)?;
    let mut out = Cursor::new(Vec::new());
    image.write_to(&mut out, image::ImageFormat::Png).ok()?;
    Some(out.into_inner())
}

/* ---------------- registry helpers ---------------- */

unsafe fn open_key(parent: HKEY, path: &str, access: REG_SAM_FLAGS) -> Result<HKEY, ()> {
    let wide_path = wide(path);
    let mut key = HKEY(std::ptr::null_mut());
    let err = RegOpenKeyExW(
        parent,
        PCWSTR(wide_path.as_ptr()),
        None,
        access | KEY_READ,
        &mut key,
    );
    if err.0 != 0 || key.0.is_null() {
        return Err(());
    }
    Ok(key)
}

/// Reads a REG_SZ / REG_EXPAND_SZ / REG_DWORD value as a string.
unsafe fn reg_string(hk: HKEY, name: &str) -> Option<String> {
    let wide_name = wide(name);
    let mut value_type = REG_VALUE_TYPE(0);
    let mut len = 0u32;
    let err = RegQueryValueExW(
        hk,
        PCWSTR(wide_name.as_ptr()),
        None,
        Some(&mut value_type),
        None,
        Some(&mut len),
    );
    if err.0 != 0 || len == 0 {
        return None;
    }
    let mut buf = vec![0u8; len as usize];
    let err = RegQueryValueExW(
        hk,
        PCWSTR(wide_name.as_ptr()),
        None,
        Some(&mut value_type),
        Some(buf.as_mut_ptr()),
        Some(&mut len),
    );
    if err.0 != 0 {
        return None;
    }
    if value_type.0 == REG_SZ.0 || value_type.0 == REG_EXPAND_SZ.0 {
        let units: Vec<u16> = buf
            .chunks_exact(2)
            .map(|c| u16::from_le_bytes([c[0], c[1]]))
            .collect();
        let end = units.iter().position(|&u| u == 0).unwrap_or(units.len());
        Some(String::from_utf16_lossy(&units[..end]).trim().to_string())
    } else if value_type.0 == REG_DWORD.0 {
        // Registry values are third-party data; guard the slice so a
        // malformed value length cannot panic the scan.
        let value = u32::from_le_bytes(buf.get(..4)?.try_into().ok()?);
        Some(value.to_string())
    } else {
        None
    }
}

/// Reports whether a registry value exists without depending on its type or
/// contents. Shell registrations use empty marker values such as NoStartPage.
unsafe fn reg_value_exists(hk: HKEY, name: &str) -> bool {
    let wide_name = wide(name);
    RegQueryValueExW(hk, PCWSTR(wide_name.as_ptr()), None, None, None, None).0 == 0
}

unsafe fn reg_dword(hk: HKEY, name: &str) -> Option<u32> {
    let wide_name = wide(name);
    let mut value_type = REG_VALUE_TYPE(0);
    let mut len = 4u32;
    let mut buf = [0u8; 4];
    let err = RegQueryValueExW(
        hk,
        PCWSTR(wide_name.as_ptr()),
        None,
        Some(&mut value_type),
        Some(buf.as_mut_ptr()),
        Some(&mut len),
    );
    if err.0 != 0 || value_type.0 != REG_DWORD.0 {
        return None;
    }
    Some(u32::from_le_bytes(buf))
}

/// Strips quotes and a trailing ",index" from a DisplayIcon value.
fn parse_icon_path(value: &str) -> Option<PathBuf> {
    let mut value = value.trim();
    if let Some((path, tail)) = value.rsplit_once(',') {
        if !tail.trim().is_empty() && tail.trim().parse::<i32>().is_ok() {
            value = path.trim();
        }
    }
    let value = value.trim_matches('"').trim();
    if value.is_empty() {
        return None;
    }
    Some(PathBuf::from(value))
}

/// Extracts the executable from an App Paths value or an Applications
/// `shell\open\command` registration. Registered commands may quote a path
/// containing spaces or append placeholders and command-line arguments.
fn parse_registered_executable(value: &str) -> Option<PathBuf> {
    let value = value.trim();
    if value.is_empty() {
        return None;
    }

    let executable = if let Some(quoted) = value.strip_prefix('"') {
        let end = quoted.find('"')?;
        &quoted[..end]
    } else {
        let lower = value.to_ascii_lowercase();
        let end = lower.find(".exe")? + ".exe".len();
        &value[..end]
    };
    let executable = executable.trim();
    (!executable.is_empty()).then(|| PathBuf::from(executable))
}

/// Finds the launcher exe inside an install folder: prefer one whose stem
/// appears in the display name, else the largest exe at the root.
fn find_exe_in(dir: &Path, display_name: &str) -> Option<PathBuf> {
    let name_lower = display_name.to_lowercase();
    let mut best: Option<(i64, PathBuf)> = None;
    for entry in std::fs::read_dir(dir).ok()?.flatten() {
        let Ok(file_type) = entry.file_type() else {
            continue;
        };
        if !file_type.is_file() {
            continue;
        }
        let path = entry.path();
        let is_exe = path
            .extension()
            .and_then(|e| e.to_str())
            .map(|e| e.eq_ignore_ascii_case("exe"))
            .unwrap_or(false);
        if !is_exe {
            continue;
        }
        let stem = path
            .file_stem()
            .map(|s| s.to_string_lossy().to_lowercase())
            .unwrap_or_default();
        if !stem.is_empty() && name_lower.contains(&stem) {
            return Some(path);
        }
        let size = path.metadata().map(|m| m.len() as i64).unwrap_or(0);
        if best.as_ref().is_none_or(|(s, _)| size > *s) {
            best = Some((size, path));
        }
    }
    best.filter(|(size, _)| *size >= 64 * 1024)
        .map(|(_, path)| path)
}

/* ---------------- string helpers ---------------- */

fn wide(s: &str) -> Vec<u16> {
    s.encode_utf16().chain(std::iter::once(0)).collect()
}

unsafe fn read_buf16(f: impl FnOnce(&mut [u16]) -> windows::core::Result<()>) -> String {
    let mut buf = [0u16; 2048];
    if f(&mut buf).is_ok() {
        wide_trim(&buf)
    } else {
        String::new()
    }
}

fn wide_trim(buf: &[u16]) -> String {
    let end = buf.iter().position(|&c| c == 0).unwrap_or(buf.len());
    String::from_utf16_lossy(&buf[..end]).trim().to_string()
}

fn clean_name(stem: &str) -> String {
    let mut name = stem.trim().to_string();
    for suffix in [" - Shortcut", " (2)", " (3)"] {
        if let Some(stripped) = name.strip_suffix(suffix) {
            name = stripped.trim().to_string();
        }
    }
    name
}

/// Expands %VAR% references using the process environment.
fn expand_env(value: &str) -> String {
    let mut out = String::with_capacity(value.len());
    let chars: Vec<char> = value.chars().collect();
    let mut i = 0;
    while i < chars.len() {
        if chars[i] == '%' {
            if let Some(end) = chars[i + 1..].iter().position(|&c| c == '%') {
                let name: String = chars[i + 1..i + 1 + end].iter().collect();
                if let Ok(v) = std::env::var(&name) {
                    out.push_str(&v);
                    i += end + 2;
                    continue;
                }
            }
        }
        out.push(chars[i]);
        i += 1;
    }
    out
}

/// Lowercased alphanumerics only, for punctuation-insensitive exact match.
fn normalize(name: &str) -> String {
    name.to_lowercase()
        .chars()
        .filter(|c| c.is_alphanumeric())
        .collect()
}

fn dedupe_keywords(keywords: Vec<String>) -> Vec<String> {
    let mut seen: HashMap<String, ()> = HashMap::new();
    keywords
        .into_iter()
        .filter_map(|kw| {
            let normalized = kw.to_lowercase();
            if normalized.trim().is_empty() {
                return None;
            }
            if seen.insert(normalized.clone(), ()).is_some() {
                return None;
            }
            Some(normalized)
        })
        .collect()
}

fn looks_virtual(target: &str) -> bool {
    let lower = target.to_lowercase();
    lower.starts_with("shell:") || lower.contains("::{")
}

fn hash(s: &str) -> String {
    let mut h: u64 = 0xcbf29ce484222325;
    for byte in s.bytes() {
        h ^= byte as u64;
        h = h.wrapping_mul(0x100000001b3);
    }
    format!("{h:016x}")
}

fn png_data_url(bytes: &[u8]) -> String {
    const TABLE: &[u8] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    let mut out = String::with_capacity(bytes.len().div_ceil(3) * 4);
    for chunk in bytes.chunks(3) {
        let b = [
            chunk[0],
            chunk.get(1).copied().unwrap_or(0),
            chunk.get(2).copied().unwrap_or(0),
        ];
        out.push(TABLE[(b[0] >> 2) as usize] as char);
        out.push(TABLE[((b[0] & 0x03) << 4 | b[1] >> 4) as usize] as char);
        out.push(if chunk.len() > 1 {
            TABLE[((b[1] & 0x0f) << 2 | b[2] >> 6) as usize] as char
        } else {
            '='
        });
        out.push(if chunk.len() > 2 {
            TABLE[(b[2] & 0x3f) as usize] as char
        } else {
            '='
        });
    }
    format!("data:image/png;base64,{out}")
}

unsafe fn known_folder(id: &GUID) -> Option<PathBuf> {
    let path = SHGetKnownFolderPath(id, Default::default(), None).ok()?;
    let text = path.to_string().unwrap_or_default();
    CoTaskMemFree(Some(path.as_ptr() as *const c_void));
    if text.is_empty() {
        None
    } else {
        Some(PathBuf::from(text))
    }
}

fn icon_cache_dir() -> PathBuf {
    unsafe {
        if let Some(appdata) = known_folder(&FOLDERID_RoamingAppData) {
            return appdata.join("app.prism.launcher").join("icons");
        }
    }
    PathBuf::from(".")
}

/// Reads a VT_LPWSTR out of a PROPVARIANT (windows-rs 0.61 exposes the raw
/// union rather than helpers).
unsafe fn prop_lpwstr(value: &PROPVARIANT) -> Option<String> {
    let inner = &value.Anonymous.Anonymous;
    if inner.vt == VT_LPWSTR {
        let ptr = inner.Anonymous.pwszVal;
        if !ptr.is_null() {
            return Some(ptr.to_string().unwrap_or_default());
        }
    }
    None
}

/* ---------------- launch ---------------- */

/// Launches an app the way the real Start menu would: shortcut-backed
/// entries run through their .lnk/.url (so the shell applies the working
/// directory, arguments and environment exactly as authored), packaged apps
/// go through shell:AppsFolder by AUMID, everything else runs the resolved
/// target directly.
pub fn launch(app: &AppEntry) -> Result<(), String> {
    unsafe {
        if let Some(path) = app.path.as_deref().filter(|path| is_executable(path)) {
            if shell_open(path, app.args.as_deref(), app.working_directory.as_deref()) {
                return Ok(());
            }
        }
        if let Some(location) = &app.location {
            if !location.is_empty()
                && Path::new(location).exists()
                && shell_open(location, None, None)
            {
                return Ok(());
            }
        }
        if let Some(aumid) = &app.aumid {
            if activate_packaged_app(aumid).is_ok() {
                return Ok(());
            }
            return explorer_arg(&format!("shell:AppsFolder\\{aumid}"));
        }
        if let Some(path) = &app.path {
            if !path.is_empty()
                && shell_open(path, app.args.as_deref(), app.working_directory.as_deref())
            {
                return Ok(());
            }
        }
        Err(format!("failed to launch {}", app.name))
    }
}

/// Launches a scanned desktop application or script through Windows' `runas`
/// verb. Packaged apps have no local process target and are intentionally not
/// eligible for elevation.
pub fn launch_elevated(app: &AppEntry) -> Result<(), String> {
    let path = app
        .path
        .as_deref()
        .map(Path::new)
        .filter(|path| path.is_absolute() && path.is_file())
        .ok_or_else(|| format!("{} cannot be run as administrator", app.name))?;
    launch_path_elevated(path, app.args.as_deref(), app.working_directory.as_deref())
}

pub fn launch_path_elevated(
    path: &Path,
    args: Option<&str>,
    working_directory: Option<&str>,
) -> Result<(), String> {
    if !path.is_file() || !is_elevatable_path(path) {
        return Err(format!(
            "{} is not a supported application or script",
            path.display()
        ));
    }

    let path_text = path.to_string_lossy();
    let extension = path
        .extension()
        .and_then(|value| value.to_str())
        .unwrap_or_default()
        .to_ascii_lowercase();
    let fallback_directory = path.parent().map(|parent| parent.to_string_lossy());
    let directory = working_directory
        .filter(|value| !value.is_empty())
        .or(fallback_directory.as_deref());
    let (target, parameters) = elevated_command(&path_text, &extension, args);

    unsafe { shell_execute("runas", &target, parameters.as_deref(), directory) }.map_err(|code| {
        if code == 5 {
            "Administrator permission was not granted".to_string()
        } else {
            format!(
                "failed to run {} as administrator (Shell error {code})",
                path.display()
            )
        }
    })
}

pub fn is_elevatable_path(path: &Path) -> bool {
    path.extension()
        .and_then(|value| value.to_str())
        .is_some_and(|extension| {
            matches!(
                extension.to_ascii_lowercase().as_str(),
                "exe" | "com" | "bat" | "cmd" | "ps1" | "vbs" | "js" | "wsf"
            )
        })
}

fn elevated_command(path: &str, extension: &str, args: Option<&str>) -> (String, Option<String>) {
    let trailing_args = args
        .filter(|value| !value.trim().is_empty())
        .map(|value| format!(" {value}"))
        .unwrap_or_default();
    match extension {
        "bat" | "cmd" => (
            "cmd.exe".to_string(),
            Some(format!("/d /s /c \"\"{path}\"{trailing_args}\"")),
        ),
        "ps1" => (
            "powershell.exe".to_string(),
            Some(format!(
                "-NoLogo -NoProfile -File \"{path}\"{trailing_args}"
            )),
        ),
        "vbs" | "js" | "wsf" => (
            "wscript.exe".to_string(),
            Some(format!("//nologo \"{path}\"{trailing_args}")),
        ),
        _ => (path.to_string(), args.map(str::to_string)),
    }
}

fn activate_packaged_app(aumid: &str) -> Result<(), String> {
    let _com = ComGuard::init();
    unsafe {
        let manager: IApplicationActivationManager =
            CoCreateInstance(&ApplicationActivationManager, None, CLSCTX_LOCAL_SERVER)
                .map_err(|error| format!("failed to create app activation manager: {error}"))?;
        let app_id = wide(aumid);
        manager
            .ActivateApplication(PCWSTR(app_id.as_ptr()), PCWSTR::null(), AO_NONE)
            .map(|_| ())
            .map_err(|error| format!("failed to activate {aumid}: {error}"))
    }
}

pub fn open_path(path: &Path) -> Result<(), String> {
    let value = path.to_string_lossy();
    if unsafe { shell_open(&value, None, None) } {
        Ok(())
    } else {
        Err(format!("failed to open {}", path.display()))
    }
}

pub fn open_path_location(path: &Path) -> Result<(), String> {
    let value = path.to_string_lossy();
    let arg = format!("/select,\"{value}\"");
    explorer_arg(&arg)
}

fn is_executable(path: &str) -> bool {
    Path::new(path)
        .extension()
        .is_some_and(|extension| extension.eq_ignore_ascii_case("exe"))
        && Path::new(path).is_file()
}

unsafe fn shell_open(path: &str, args: Option<&str>, working_directory: Option<&str>) -> bool {
    shell_execute("open", path, args, working_directory).is_ok()
}

unsafe fn shell_execute(
    operation: &str,
    path: &str,
    args: Option<&str>,
    working_directory: Option<&str>,
) -> Result<(), isize> {
    let file = wide(path);
    let operation = wide(operation);
    let params = args.map(wide);
    let directory = working_directory
        .filter(|value| !value.is_empty())
        .map(wide);
    let result = ShellExecuteW(
        None,
        Some(&PCWSTR(operation.as_ptr())),
        PCWSTR(file.as_ptr()),
        params.as_deref().map(|v| PCWSTR(v.as_ptr())).as_ref(),
        directory
            .as_deref()
            .map(|value| PCWSTR(value.as_ptr()))
            .as_ref(),
        SW_SHOWNORMAL,
    );
    // HINSTANCE values > 32 mean success; lower values are Shell error codes.
    let code = result.0 as isize;
    if code > 32 {
        Ok(())
    } else {
        Err(code)
    }
}

fn explorer_arg(arg: &str) -> Result<(), String> {
    Command::new("explorer.exe")
        .arg(arg)
        .spawn()
        .map(|_| ())
        .map_err(|e| format!("failed to launch: {e}"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn elevated_targets_are_limited_to_apps_and_supported_scripts() {
        for path in [
            "tool.exe",
            "tool.COM",
            "setup.bat",
            "setup.CMD",
            "task.ps1",
            "task.vbs",
            "task.js",
            "task.wsf",
        ] {
            assert!(is_elevatable_path(Path::new(path)), "should allow {path}");
        }
        for path in ["notes.txt", "archive.zip", "shortcut.lnk", "folder", ""] {
            assert!(!is_elevatable_path(Path::new(path)), "should reject {path}");
        }
    }

    #[test]
    fn elevated_script_commands_use_the_expected_windows_hosts() {
        assert_eq!(
            elevated_command(r"C:\Tools\deploy.cmd", "cmd", Some("--quiet")),
            (
                "cmd.exe".to_string(),
                Some(r#"/d /s /c ""C:\Tools\deploy.cmd" --quiet""#.to_string())
            )
        );
        assert_eq!(
            elevated_command(r"C:\Tools\deploy.ps1", "ps1", None),
            (
                "powershell.exe".to_string(),
                Some(r#"-NoLogo -NoProfile -File "C:\Tools\deploy.ps1""#.to_string())
            )
        );
        assert_eq!(
            elevated_command(r"C:\Tools\deploy.vbs", "vbs", None),
            (
                "wscript.exe".to_string(),
                Some(r#"//nologo "C:\Tools\deploy.vbs""#.to_string())
            )
        );
    }

    #[test]
    #[ignore = "scans the real machine (shortcut roots, AppsFolder, icon extraction); run explicitly with cargo test -- --ignored"]
    fn scan_produces_valid_cached_entries() {
        let tmp =
            std::env::temp_dir().join(format!("prism-test-apps-cache-{}.json", std::process::id()));
        let _ = std::fs::remove_file(&tmp);
        let apps = scan(&tmp).expect("scan should succeed");
        assert!(!apps.is_empty(), "the Windows runner should expose apps");
        assert!(
            apps.iter().any(|app| app.icon.is_some()),
            "at least one discovered app should have an icon"
        );
        // Every entry needs a stable id and searchable metadata.
        for app in &apps {
            assert!(!app.name.is_empty(), "empty name");
            assert!(!app.app_id.is_empty(), "empty app id");
            assert_eq!(app.normalized_name, normalize(&app.name));
        }
        let inbox_apps: Vec<_> = apps
            .iter()
            .filter(|app| {
                app.aumid.as_deref().is_some_and(|aumid| {
                    [
                        "Microsoft.WindowsCalculator_",
                        "Microsoft.WindowsCamera_",
                        "Microsoft.WindowsAlarms_",
                        "Microsoft.WindowsStore_",
                    ]
                    .iter()
                    .any(|prefix| aumid.starts_with(prefix))
                })
            })
            .collect();
        for app in inbox_apps {
            assert!(
                app.icon.is_some(),
                "installed packaged app {} should expose its Shell logo",
                app.name
            );
        }
        let cached = load_cache(&tmp).expect("scan cache should be readable");
        assert_eq!(cached.len(), apps.len());
        let _ = std::fs::remove_file(tmp);
    }

    #[test]
    fn name_helpers() {
        assert_eq!(clean_name("Discord - Shortcut"), "Discord");
        assert_eq!(clean_name("Fortnite (2)"), "Fortnite");
        assert_eq!(normalize("Visual Studio Code"), "visualstudiocode");
        assert_eq!(normalize("C++ (x64)"), "cx64");
        assert!(looks_virtual("shell:AppsFolder\\x!y"));
        assert!(looks_virtual("::{20D04FE0-3AEA-1069-A2D8-08002B30309D}"));
        assert!(!looks_virtual("C:\\Program Files\\app.exe"));
    }

    #[test]
    fn icon_parsing() {
        assert_eq!(
            parse_icon_path(r#""C:\Apps\Thing\app.exe",0"#),
            Some(PathBuf::from(r"C:\Apps\Thing\app.exe"))
        );
        assert_eq!(
            parse_icon_path(r"C:\Apps\Thing\app.exe,0"),
            Some(PathBuf::from(r"C:\Apps\Thing\app.exe"))
        );
        assert_eq!(
            parse_icon_path(r"C:\Apps\Thing\app.ico"),
            Some(PathBuf::from(r"C:\Apps\Thing\app.ico"))
        );
        assert_eq!(parse_icon_path(""), None);
    }

    #[test]
    fn registered_command_parsing() {
        assert_eq!(
            parse_registered_executable(r#""C:\Apps\Thing\app.exe""#),
            Some(PathBuf::from(r"C:\Apps\Thing\app.exe"))
        );
        assert_eq!(
            parse_registered_executable(r#""C:\Program Files\Thing\app.exe" "%1""#),
            Some(PathBuf::from(r"C:\Program Files\Thing\app.exe"))
        );
        assert_eq!(
            parse_registered_executable(r"C:\Apps\Thing\app.exe /open %1"),
            Some(PathBuf::from(r"C:\Apps\Thing\app.exe"))
        );
        assert_eq!(parse_registered_executable("not an application"), None);
        assert_eq!(parse_registered_executable(""), None);
    }

    #[test]
    fn recognizes_direct_executables_only_when_they_exist() {
        let current = std::env::current_exe().expect("current test executable");
        assert!(is_executable(&current.to_string_lossy()));
        assert!(!is_executable(r"C:\missing\app.exe"));
        assert!(!is_executable(r"C:\missing\app.lnk"));
    }

    #[test]
    fn base64_roundtrip() {
        let png = png_data_url(&[0, 1, 2, 3, 255, 254, 253]);
        assert!(png.starts_with("data:image/png;base64,"));
        assert!(png.len() > 30);
    }
}

#[cfg(test)]
mod hang_debug {
    use super::*;
    use std::cell::Cell;
    use std::time::Instant;

    /// Manual profiling harness: runs a full machine scan with a cold icon
    /// cache. Not a unit test - run explicitly with `cargo test -- --ignored`.
    #[test]
    #[ignore]
    fn hang_debug() {
        let _com = ComGuard::init();
        let tmp = std::env::temp_dir().join(format!("prism-cold-icons-{}", hash("x")));
        let _ = std::fs::remove_dir_all(&tmp);
        let mut ctx = ScanCtx {
            icons: IconCache::new(tmp),
            seen: HashMap::new(),
            apps: Vec::new(),
        };
        let t0 = Instant::now();
        let last = Cell::new(0usize);
        let on_add = |ctx: &mut ScanCtx| {
            let n = ctx.apps.len();
            if n - last.get() >= 25 {
                last.set(n);
                eprintln!("...{} apps in {:?}", n, t0.elapsed());
            }
        };
        ctx.scan_shortcut_roots();
        eprintln!("shortcuts: {} apps in {:?}", ctx.apps.len(), t0.elapsed());
        on_add(&mut ctx);
        ctx.scan_apps_folder();
        eprintln!("appsfolder: {} apps in {:?}", ctx.apps.len(), t0.elapsed());
        on_add(&mut ctx);
        ctx.scan_registry();
        eprintln!("registry: {} apps in {:?}", ctx.apps.len(), t0.elapsed());
        on_add(&mut ctx);
        ctx.scan_registered_apps();
        eprintln!(
            "registered apps: {} apps in {:?}",
            ctx.apps.len(),
            t0.elapsed()
        );
        on_add(&mut ctx);
        ctx.scan_program_files();
        eprintln!(
            "programfiles: {} apps in {:?}",
            ctx.apps.len(),
            t0.elapsed()
        );
    }
}
